### DISCUSSION TITLE
主题相关：请问fcitx5的候选窗口是否支持数字和候选词分别设置字体和颜色？

### DISCUSSION THREAD

**Discussion by tankb52** [fcitx/fcitx5#1032] [Q&A] [answered]
如题，例如我输入字母 a, 得到候选 【 1. 啊 2. 阿 3. 爱】，请问这候选窗口中的数字123 和候选词能否单独设置字体和颜色？

github上面找到的主题似乎都没有这方面的设置，是不支持吗？

另外，切换成fcitx5-rime 输入法后，候选框变成 【 1 啊  2 阿 3 爱】，数字和候选词没有了句点，这方面需要显示出句点的话，是由 fcitx5来处理 ，还是需要修改 rime 的主题文件？

OS: Debian GNU/Linux trixie/sid x86_64
Kernel: 6.6.15-amd64
fcitx5 ver: 5.1.7

**Comment by wengxt** [comment, marked as answer]
是的不支持

想要 rime 加个点可以改 rime 的设置
例

```
patch:
  menu:
    page_size: 7
    alternative_select_labels: [甲, 乙, 丙, 丁, 戊, 己, 庚, 辛, 壬, 癸]
```
