### DISCUSSION TITLE
Can I execute the Fcitx5 Input Window without using XWayland?

### DISCUSSION THREAD

**Discussion by yutkat** [fcitx/fcitx5#895] [Q&A] [answered]
Right now I am using fcitx5 in hyprland and it works fine in the Wayland environment, but I am concerned that the popup window is working in Xwayland.
Is it possible to run it without XWayland?

Does the following document apply to that description?

https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#Support_in_Wayland_Compositor

```
Window 557f9c371410 -> Fcitx5 Input Window:
        mapped: 0
        hidden: 0
        at: 267,64
        size: 104,58
        workspace: 1 (1)
        floating: 1
        monitor: 1
        class:
        title:
        initialClass: fcitx
        initialTitle: Fcitx5 Input Window
        pid: 3161859
        xwayland: 1
        pinned: 0
        fullscreen: 0
        fullscreenmode: 0
        fakefullscreen: 0
        grouped: 0
        swallowing: 0
```
