### ISSUE TITLE
how to set default IM to English

### ISSUE THREAD

**Issue by Huangyong657** [fcitx/fcitx5#1148]
### Summary

I use fcitx as inputing method. I use qt dbus to convert order for fcitx. when I restart my system(debian11), the default IM is pinyin. My system do not have UI interface, so I would like to ask how  to modify the file(which file) to set default IM to English. Thanks for your response.
                                                                                                                                                                                              yours
                                                                                                                                                                                     
                                                                                                                                                                           3150100658@zju.edu.cn

**Comment by wengxt** [comment]
There's an profile in this blog that you can take as an example.

https://www.csslayer.info/wordpress/fcitx-dev/a-new-pinyin-input-method-that-might-be-slightly-better-than-sunpinyin/

**Comment by ameaninglessname** [comment]
问了下ai：
在`/home/USERNAME/.local/share/fcitx5/rime/`的`default.custom.yaml`中写入：

```yaml
patch:
  schema:
    - schema: xkb::us  # 设置默认输入法为美式英文键盘 <- 主要是这行
    - schema: luna_pinyin # 或者你选择的其他Rime方案，例如：terra_pinyin
  engine:  # 其他引擎设置，根据需要调整
```
